# Generated by Django 2.2.3 on 2019-08-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_cust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust',
            name='CustCont',
            field=models.CharField(max_length=10),
        ),
    ]
