# Generated by Django 2.2.3 on 2019-08-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20190821_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('AdminPass', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'FP_Admin',
            },
        ),
    ]
