# Generated by Django 2.2.3 on 2019-08-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartId', models.AutoField(primary_key=True, serialize=False)),
                ('CustEmail', models.CharField(max_length=50)),
                ('FoodId', models.CharField(max_length=50)),
                ('FoodQuant', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'FP_Cart',
            },
        ),
    ]
