# Generated by Django 2.2.4 on 2020-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_auto_20200218_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Address',
            field=models.CharField(default='', max_length=150),
        ),
    ]
